### ISSUE TITLE
Tracker: Python documentation improvements

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/pydeck#11]
### Examples
- [ ] Full screen button (and deck.gl docs) buttons are below the code. Full screen button should be directly below the live example.
- [ ] deck.gl / pydeck attribution widget - This is a general issue. Right now, especially the full screen examples have two mapbox attributions, which is very misleading.

### TOC
- [ ] main page should be listed within ToC. Right now I have to click on top `pydeck` title. 

### Footer
- [ ] Copyright notice and sphinx build note do not add much and are inconsistent with the rest of our docs.

### Front page
- [ ] Add a section with contributing companies (Uber/Unfolded etc).

**Comment by ibgreen** [comment]
@kashuk Please add items based on your review of the pydeck.gl site.
